### ISSUE TITLE
License for collaborative projects where partner has different license requirements

### ISSUE THREAD

**Issue by lhsu-usgs** [usgs/best-practices#31]
Hi all,

There is a nice issue already open on [Licensing plain language & best practices](https://github.com/usgs/best-practices/issues/19), but I have a specific question that I couldn't figure out from the existing content:

In the case of a collaboration between USGS and an external partner, where there is funding from both USGS and the NASA AIST program:
"It turns out that this NASA AIST opportunity requires the use of an Apache open source software license. Could we use the Apache license with the USGS-funded software, and thus easily expand on it for NASA AIST?"

(i.e. is Public Domain "obviously" meeting the intent of having an Apache open source software license?)

Thanks.
Leslie

**Comment by emartinez-usgs** [comment]
I would caution against thinking that "public domain" and "open source" are one in the same.

I think this is covered in [IM-OSQI-2016-01 Section 2 Paragraphs E and F](https://www2.usgs.gov/usgs-manual/im/IM-OSQI-2016-01.html). Basically, the default answer is to place software releases into the public domain, use of CC0 1.0 is acceptable if necessary however, deviations from this license may exist if:

- the Apache license was stipulated in the original agreement
- parts of the software are developed with separate funding (including pre-existing software) under the Apache license

Refer to the full IM for more details.
