### ISSUE TITLE
How does this policy relate to products that are deployed and managed via Continuous Integration and Continuous Delivery pipelines  

### ISSUE THREAD

**Issue by jkreft-usgs** [usgs/best-practices#34]
Some USGS web applications are managed using agile processes, and are released to production as often as several times a day using continuous integration tools such as Jenkins or Travis that automate tasks such as testing, packaging and deployment.  How can these kinds of rapid-release approaches, which have been proven to be the most effective software development approach, be reconciled with the idea that a "release" needs to be run through IPDS?  

One option may be that a given organization may also have the option of developing and approving a software management policy that lays out the best practices that the organization expect to follow and how their tooling will allow for following and documentation of Fundamental Science Practices without the organizational burden of hundreds or even thousands of additional IPDS records per year.

**Comment by emartinez-usgs** [comment]
I think we talked a bit about this in #22. There was no specific resolution determined, but does this seem different enough to keep as a separate issue or can we continue to discuss over in #22 instead?

**Comment by jkreft-usgs** [comment]
#22 is definitely similar, and @cschroed-usgs basically brought up the same point over there.  I'm fine with continuing the discussion on #22, though we may want to modify the title so that others see the relevancy.

**Comment by emartinez-usgs** [comment]
Issue #22 is now linked with this issue so users should have no problem finding the correct place to discuss CI/CD. Closing this issue for now and we can continue discussion in #22.
