### ISSUE TITLE
DOI Root Certificate no longer available from DOI

### ISSUE THREAD

**Issue by isuftin** [usgs/best-practices#40]
https://github.com/usgs/best-practices/blob/master/UsingGitWithHTTPSInterception.md links to the now defunct DOI Root certificate link.

DOI does not provide guidance as to where end users should get the DOI Root certificate. This page should change its wording to not directly link to a missing resource but I am not sure what current guidance should now be.

Thoughts?

**Comment by isuftin** [comment]
It seems as though the certificate is currently at http://pki2.doi.net/CertEnroll/IINDENORCA01_DOIRootCA2.crt in DER format.

To convert to PEM format, we can use the openssl utility: `openssl x509 -inform der -in /path/to/certificate.crt -out /path/to/output/pem/format.pem`

**Comment by jmfee-usgs** [comment]
It is also available here:
https://github.com/usgs/hazdev-base-images/blob/master/centos/DOIRootCA2.crt

**Comment by cschroed-usgs** [comment]
A conversation on the SSL Intercept team mailing list (ssl_decryption@ios.doi.gov) revealed that we should use this URL:
http://sslhelp.doi.net/docs/DOIRootCA2.cer

**Comment by dblodgett-usgs** [comment]
That latest URL no longer resolves. Is there a new location we should be using?

**Comment by dblodgett-usgs** [comment]
OK, nevermind. sslhelp.doi.net is behind the firewall.
