### ISSUE TITLE
Slack channel?

### ISSUE THREAD

**Issue by mguy-usgs** [usgs/best-practices#46]
At CDI there was discussion of a slack channel to have software conversations. Should we create a new team, something like usgs-software? Or should we create a usgs team and have a software channel? There are multiple USGS teams out there already, the ones I could find are: ghsc, wim-usgs, usgs-mobile, and usgs-astrogeology.

Thoughts?

**Comment by mguy-usgs** [comment]
I *think* software is a topic, thus a channel, under a broader team, like usgs. Where as teams like wim and ghsc are actually teams as already structured. So I suggest we make a usgs team, and make a software channel.

Thoughts?

**Comment by emartinez-usgs** [comment]
I'm checking our options...

**Comment by lhsu-usgs** [comment]
I like this idea. I think the ESIP Slack channel works well, even though there are 32 channels, including general and random, it's not overwhelming to me (maybe because post frequency is not overwhelming). If we did have an overarching usgs team, would it be reasonable to have channels like usgs-cdi, usgs-cdi-techstack, etc?

**Comment by emartinez-usgs** [comment]
I think within the context of a "usgs" team, prefixing each channel with "usgs-" is a bit redundant. While channels are a great way to separate conversations they can also lead to fragmentation or questions like, "which channel should I use?".

As you say, typically these channels are fairly quite so I'm not sure we need super narrow topics. M2C.

**Comment by mguy-usgs** [comment]
technology changes imminent, so hold off for now...more to come later...

**Comment by cschroed-usgs** [comment]
Other relevant Slacks include:
https://usgs.slack.com/
https://usgs-cida.slack.com

**Comment by cschroed-usgs** [comment]
I like the idea of making a software channel within the usgs team.
