### ISSUE TITLE
best-practices code.json failing validator?

### ISSUE THREAD

**Issue by rsignell-usgs** [usgs/best-practices#73]
I tried running
https://github.com/usgs/best-practices/blob/master/code.json
through the Code.json 2.2.0 validator at:
https://code.gov/#/policy-guide/docs/compliance/inventory-code/tools/validate-schema
and after removing the opening and closing square brackets, I get:
```
Property name is not allowed (2, 5)
Property organization is not allowed (3, 5)
Property description is not allowed (4, 5)
Property status is not allowed (6, 5)
Property permissions is not allowed (8, 5)
Property homepageURL is not allowed (18, 5)
Property downloadURL is not allowed (19, 5)
Property disclaimerURL is not allowed (20, 5)
Property vcs is not allowed (22, 5)
Property laborHours is not allowed (24, 5)
Property tags is not allowed (26, 5)
Missing property "measurementType" (1, 3)
Missing property "releases" (1, 3)
Missing property "agency" (1, 3)
Property repositoryUrl is not allowed (21, 5)
Property languages is not allowed (33, 5)
Property contact is not allowed (37, 5)
Property date is not allowed (42, 5)
```
Does anyone know if these problems are caused by:

* actual code.json error
* validation application error
* user error
😛

**Comment by cschroed-usgs** [comment]
Interesting! I'm not sure.

I know there is a separate repo for generating the USGS code.json
https://github.com/usgs/code-json-generator
Should this issue be raised over there?

I wonder why both the repos have a code.json?

**Comment by rsignell-usgs** [comment]
Here's an example `code.json` that produces no errors in the validation tool, from 
https://github.com/GSA/code-gov-web/blob/master/src/assets/sample_code_200.json
```
{
  "version": "2.0.0",
  "measurementType": {
    "method": "linesOfCode"
  },
  "agency": "DOABC",
  "releases": [
    {
      "name": "mygov",
      "version": "1.0.0",
      "organization": "XYZ Department",
      "description": "A Platform for Connecting People and Government",
      
      "permissions": {
        "licenses": [
        {
          "URL": "https://path.to/license",
          "name": "CC0"
        }
      ],
        "usageType": "openSource",
        "exemptionText": null
      },
      "tags": [
        "platform",
        "government",
        "connecting",
        "people"
      ],
      "contact": {
        "email": "release@agency.gov",
        "name": "Project Coordinator Name",
        "URL": "https://twitter.com/projectname",
        "phone": "2025551313"
      },
      "status": "Alpha",
      "vcs": "git",
      "repositoryURL": "https://github.com/presidential-innovation-fellows/code-gov-web",
      "homepageURL": "https://agency.gov/project-homepage",
      "downloadURL": "https://agency.gov/project/dist.tar.gz",
      "languages": [
        "java",
        "python"
      ],
      "laborHours": 1000,
      "relatedCode": [
        {
          "name": "Code.gov API",
          "URL": "https://github.com/presidential-innovation-fellows/code-gov-api"
   
        }
      ],
      "reusedCode": [
        {
          "name": "US web design standards",
          "URL": "https://github.com/18F/web-design-standards"
          
        }
      ],
      "partners": [
        {
          "name": "DOXYZ",
          "email": "releaseContact1@doxyz.gov"
        }
      ],
      "date": {
        "created": "2016-04-12",
        "lastModified": "2016-04-12",
        "metadataLastUpdated": "2016-04-13"
      }
    }
  ]
}
```

**Comment by rsignell-usgs** [comment]
@mbucknell , does that check the schema or just whether it's valid json?
I used the cod.gov validator written specifically for `code.json` (version 2.2.0) here: 
https://code.gov/#/policy-guide/docs/compliance/inventory-code/tools/validate-schema

**Comment by mbucknell** [comment]
It doesn't. It looks like the code.json in best practices passes version 1.0.1 of the schema but not version 2.0.0

**Comment by rsignell-usgs** [comment]
So I guess we need to decide whether we are recommending people write code.json v 1.0.1, or whether we are recommending v 2.0.0.     We should specify which one here: https://github.com/usgs/best-practices/blob/c53fefa89799f4adca6e925bd0e420dd2e8b736f/software/metadata.md

I perhaps mistakenly assumed that we were shooting for 2.0.0 because of the commit comment here: 
https://github.com/usgs/best-practices/commit/e9e80db42655c3c906f667b5048983e0efdce0fb

**Comment by emartinez-usgs** [comment]
The `code.json` file found at the repository root of a project is a "snippet" containing an array of "releases" for the current project. It is not a full inventory itself, but rather it is intended to be incorporated into the inventory generated by https://github.com/usgs/code-json-generator .

I'll admit, since they are are both called "code.json" this can be confusing.

The snippet is compliant with the 2.x code.gov specification for "releases" and I think the latest version (2.x) is desirable. Up-converters can be made available if/when 3.x+ are released so advocating for 2.x currently seems ideal.

**Comment by rsignell-usgs** [comment]
Ah okay, thanks @emartinez-usgs for the clarification!
