### ISSUE TITLE
Update guidance on how to become a member of the USGS organization

### ISSUE THREAD

**Issue by mbucknell** [usgs/best-practices#84]
It looks like we need to open an issue in the USGS gitlab. Could the guidance be updated to indicate this?

**Comment by emartinez-usgs** [comment]
Unfortunately, the page to request joining the USGS Organization on GitHub is internal access only, so we can't publicize it here. The intent is for users to email the support group and we can direct users appropriately from there. This isn't ideal and will likely change in the coming months as DOI formalizes its presence at the department level.
